name: K6 Smoke Test
on:
  push:
    branches: [k6-ci-test]

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build k6 script
        run: |
          npm ci
          npx webpack
          ls dist/mixed-scenario-v2.js   # 确认产物存在

      - name: Run k6
        uses: grafana/k6-action@v0.3.1
        with:
          path: ./dist/mixed-scenario-v2.js
